// auto-generated by circomkit
pragma circom 2.0.0;

include "../privacyPool.circom";

component main {public[publicVal, signalHash, merkleProofLength, inputNullifier, outCommitment]} = PrivacyPool(32, 2, 2);
