import type { Address } from "viem"
import type { Chain } from "viem/chains"
import { sepolia, gnosis } from "viem/chains"
import type { PrivacyPoolMeta } from "@privacy-pool-v1/contracts"

/// TODO: This file should be generated by the deployment script
export const ExistingPrivacyPools: Map<Chain, PrivacyPoolMeta[]> = new Map<
  Chain,
  PrivacyPoolMeta[]
>([
  [
    sepolia,
    [
      {
        chain: sepolia,
        id: "Sepolia Eth Pool 1",
        address: "0x8f50067dfC867fA2f102c93c192790b61DC70721" as Address,
        verifier: "0x7109fa91D440b5c723E1B5cc8098D14Ea7e6CF43" as Address,
        scope:
          17860360484857216088464258890461544313806446338584014491183282033613384044019n,
        genesis: 6179793n,
        unitRepresentative: "ETH", // reference by ticker
        minmaxCommitValue: [0n, 1000000000000000000n]
      }
    ]
  ],
  [
    gnosis,
    [
      {
        chain: gnosis,
        id: "Gnosis xDAI Pool 1",
        address: "0x52e41dc97ffcc4b67bd50c4253554ea73317be07" as Address,
        verifier: "0x8c6561ca85229fd0b2a3d652d1734e60f9f57140" as Address,
        genesis: 34635522n,
        unitRepresentative: "xDAI", // reference by ticker
        minmaxCommitValue: [0n, 1000000000000000000n]
      }
    ]
  ]
])
