import type { Address } from "viem"
import type { Chain } from "viem/chains"
import { sepolia, gnosis } from "viem/chains"
import type { PrivacyPoolMeta } from "@privacy-pool-v1/contracts"

export const SUPPORTED_CHAINS = [sepolia, gnosis]
export const DEFAULT_CHAIN = sepolia

/// TODO: This file should be generated by the deployment script
export const ExistingPrivacyPools: Map<Chain, PrivacyPoolMeta[]> = new Map<
  Chain,
  PrivacyPoolMeta[]
>([
  [
    sepolia,
    [
      {
        chain: sepolia,
        id: "Sepolia Eth Pool 1",
        address: "0x8f50067dfC867fA2f102c93c192790b61DC70721" as Address,
        verifier: "0x7109fa91D440b5c723E1B5cc8098D14Ea7e6CF43" as Address,
        scope:
          17860360484857216088464258890461544313806446338584014491183282033613384044019n,
        genesis: 6179793n,
        unitRepresentative: "ETH", // reference by ticker
        minmaxCommitValue: [0n, 1000000000000000000n]
      }
    ]
  ],
  [
    gnosis,
    [
      {
        chain: gnosis,
        id: "Gnosis xDAI Pool 1",
        address: "0x6e997b9291F32DA0319F1DFc4B84186085492B8d" as Address,
        verifier: "0x19427f691bF4E73A1d88EE974277F7Cc3D086b88" as Address,
        genesis: 34635522n,
        scope:
          19925016578215552840965678320606972188524212792772556824624777299752266280250n,
        unitRepresentative: "xDAI", // reference by ticker
        minmaxCommitValue: [0n, 1000000000000000000n]
      }
    ]
  ]
])
