// auto-generated by circomkit
pragma circom 2.1.8;

include "../privacyPool.circom";

component main {public[publicVal, signalHash, merkleProofLength, inputNullifier, outCommitment]} = PrivacyPool(20, 2, 2);
