// auto-generated by circomkit
pragma circom 2.1.8;

include "../txRecordStep.circom";

component main {public[step_in]} = txRecordStep(23, 2, 2, 11850551329423159860688778991827824730037759162201783566284850822760196767874);
