// auto-generated by circomkit
pragma circom 2.1.9;

include ".././privacy-pool/privacyPool.circom";

component main {public[publicVal, signalHash, actualMerkleTreeDepth, inputNullifier, outCommitment]} = PrivacyPool(32, 2, 2);
