[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache_forge'
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "./test/test-data" },
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
gnosis = { key = "${ETHERSCAN_API_KEY}" }
