// auto-generated by circomkit
pragma circom 2.0.0;

include "../txRecordStep.circom";

component main {public[stepIn, associationMerkleRoot, expectedPathIndices]} = txRecordStep(23, 2, 2, 11850551329423159860688778991827824730037759162201783566284850822760196767874);
